wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1681924140.827416
    t:
      1:
      - 1
      - 3
      - 55
      2:
      - 1
      - 3
      - 55
      3:
      - 1
      - 5
      - 13
      - 14
      - 19
      - 23
      - 24
      - 34
      4: 3.7.9
      5: 0.13.10
      8:
      - 3
      - 5
magic:
  desc: null
  value:
    enable: true
